// import './Decorator'
// import './Heritage'
// import './Composition'
// import './Abstract'
// import './Bridge'
// import './Observer'
// import './Observer/ex002'
// import './Proxy'
import './Proxy/ex0001'